import { Queue, Worker, Job } from 'bullmq';
import { GitHubService } from './githubService';
import { AnalyzerService } from './analyzerService';
import { PRAnalysisJobData } from '../types';

/**
 * Service to manage background job scheduling and execution using Redis and BullMQ.
 */
export class QueueService {
  private static prQueue: Queue;
  private static prWorker: Worker;
  public static readonly QUEUE_NAME = 'pr-review';

  /**
   * Initialize the Redis connection and the job queue.
   */
  public static initialize(): void {
    if (this.prQueue) return;

    const redisUrl = process.env.REDIS_URL || 'redis://127.0.0.1:6379';
    let connectionOpts: any;

    try {
      const parsedUrl = new URL(redisUrl);
      connectionOpts = {
        host: parsedUrl.hostname,
        port: parsedUrl.port ? parseInt(parsedUrl.port, 10) : 6379,
        username: parsedUrl.username || undefined,
        password: parsedUrl.password || undefined,
        maxRetriesPerRequest: null, // Critical configuration required by BullMQ
      };
      console.log(`Configuring BullMQ Redis connection targeting ${parsedUrl.hostname}:${parsedUrl.port || 6379}`);
    } catch (err: any) {
      console.error('Failed to parse REDIS_URL, falling back to localhost options:', err.message);
      connectionOpts = {
        host: '127.0.0.1',
        port: 6379,
        maxRetriesPerRequest: null,
      };
    }

    this.prQueue = new Queue(this.QUEUE_NAME, {
      connection: connectionOpts,
      defaultJobOptions: {
        attempts: 3,
        backoff: {
          type: 'exponential',
          delay: 5000, // 5s, 10s, 20s
        },
        removeOnComplete: true, // Clean up successful jobs automatically
        removeOnFail: false,    // Keep failed jobs for debugging/visibility
      },
    });
  }

  /**
   * Get the queue instance, initializing it if necessary.
   */
  public static getQueue(): Queue {
    if (!this.prQueue) {
      this.initialize();
    }
    return this.prQueue;
  }

  /**
   * Add a PR analysis task to the job queue.
   */
  public static async addAnalysisJob(jobData: PRAnalysisJobData): Promise<Job> {
    const queue = this.getQueue();
    const jobName = `analyze-${jobData.repo_name.replace('/', '-')}-${jobData.pr_id}`;
    return await queue.add(jobName, jobData);
  }

  /**
   * Start the background worker process to consume and execute queued tasks.
   */
  public static startWorker(): void {
    if (this.prWorker) return;
    
    const redisUrl = process.env.REDIS_URL || 'redis://127.0.0.1:6379';
    let connectionOpts: any;

    try {
      const parsedUrl = new URL(redisUrl);
      connectionOpts = {
        host: parsedUrl.hostname,
        port: parsedUrl.port ? parseInt(parsedUrl.port, 10) : 6379,
        username: parsedUrl.username || undefined,
        password: parsedUrl.password || undefined,
        maxRetriesPerRequest: null,
      };
    } catch (err) {
      connectionOpts = {
        host: '127.0.0.1',
        port: 6379,
        maxRetriesPerRequest: null,
      };
    }

    this.prWorker = new Worker(
      this.QUEUE_NAME,
      async (job: Job) => {
        const { repo_name, pr_id, author, commit_sha } = job.data as PRAnalysisJobData;
        console.log(`[Worker] Processing Job ID ${job.id} | PR #${pr_id} on ${repo_name}`);

        try {
          // Step 1: Fetch raw unified diff from GitHub
          const diff_text = await GitHubService.fetchPRDiff(repo_name, pr_id);
          
          // Step 2: Send payload to Python FastAPI analyzer service
          const analysisResponse = await AnalyzerService.analyzePR({
            pr_id,
            repo_name,
            diff_text: diff_text || '',
            author,
            commit_sha,
          });

          const { review_markdown, severity, flags } = analysisResponse;

          // Step 3: Format the response nicely and post it to GitHub PR as a comment
          const formattedComment = `### 🔍 ArchitectLens PR Review

**Review Summary**
- **Severity Level:** \`${severity.toUpperCase()}\`
- **Identified Flags:** ${flags.map(f => `\`${f}\``).join(', ') || '*None*'}

${review_markdown}

---
*Generated by ArchitectLens*`;

          await GitHubService.postPRComment(repo_name, pr_id, formattedComment);
          console.log(`[Worker] Job ID ${job.id} completed successfully for PR #${pr_id}.`);
          return { status: 'success', pr_id, severity };
        } catch (error: any) {
          console.error(`[Worker] Error processing Job ID ${job.id}: ${error.message}`);
          throw error; // Re-throw to trigger BullMQ retry/backoff
        }
      },
      {
        connection: connectionOpts,
      }
    );

    // Worker Event Listeners
    this.prWorker.on('completed', (job: Job | undefined, result: any) => {
      console.log(`[Worker] Job ${job?.id} finished successfully. Result:`, result);
    });

    this.prWorker.on('failed', (job: Job | undefined, err: Error) => {
      console.error(`[Worker] Job ${job?.id} failed after attempts. Error: ${err.message}`);
    });

    this.prWorker.on('error', (err: Error) => {
      console.error('Worker internal error:', err);
    });

    console.log('[Worker] Background processing worker started.');
  }

  /**
   * Gracefully close connections.
   */
  public static async close(): Promise<void> {
    if (this.prWorker) {
      await this.prWorker.close();
    }
    if (this.prQueue) {
      await this.prQueue.close();
    }
  }
}
